apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" . }}
data:
  myvalue: "Hello World"  
  {{- $relname := .Release.Name }}
  {{- with .Values.favorite }}
  release: {{ $relname }}
  the-drink: {{ .drink | repeat 5 | quote }}
  {{- if eq .drink "coffee" }}
  mug: true
  {{- end }}
  the-color: {{ .color | default "green" | quote }}
  the-food: {{ .food | upper | quote }}
  toppings: |-
    {{- range $index, $topping := $.Values.pizzaToppings }}
    - {{ $index }}: {{ $topping | title | quote }}
    {{- end }}  
  {{- end }}
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  date: {{ now }}
  date-html: {{ now | htmlDate }}
